import type { Product, Category, Order, User } from '@/lib/types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Entertainment',
    slug: 'entertainment',
    description: 'Streaming, gaming, and more for your entertainment needs.',
    imageUrl: 'https://picsum.photos/seed/cat1/600/400',
    imageHint: 'cinema screen',
  },
  {
    id: '2',
    name: 'Social Media',
    slug: 'social-media',
    description: 'Enhance your social media experience with premium features.',
    imageUrl: 'https://picsum.photos/seed/cat2/600/400',
    imageHint: 'social network',
  },
  {
    id: '3',
    name: 'Professional',
    slug: 'professional',
    description: 'Tools and services to boost your career and productivity.',
    imageUrl: 'https://picsum.photos/seed/cat3/600/400',
    imageHint: 'office meeting',
  },
  {
    id: '4',
    name: 'Music',
    slug: 'music',
    description: 'Listen to your favorite music ad-free and offline.',
    imageUrl: 'https://picsum.photos/seed/cat4/600/400',
    imageHint: 'headphones concert',
  },
];

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'YouTube Premium',
    slug: 'youtube-premium',
    description: 'Ad-free YouTube and YouTube Music.',
    longDescription: 'Enjoy YouTube and YouTube Music ad-free, offline, and in the background. Your membership also includes access to YouTube Originals.',
    price: 1200,
    originalPrice: 1500,
    imageUrl: 'https://picsum.photos/seed/prod1/600/400',
    imageHint: 'video play button',
    category: 'Entertainment',
    isFeatured: true,
    isBestSelling: true,
    releaseDate: '2023-10-01T12:00:00Z',
  },
  {
    id: 'prod_002',
    name: 'Facebook Premium',
    slug: 'facebook-premium',
    description: 'Enhanced features for your Facebook profile.',
    longDescription: 'Get a verified badge, proactive account protection, and access to exclusive stickers. Show your support and get more from the apps you love.',
    price: 950,
    imageUrl: 'https://picsum.photos/seed/prod2/600/400',
    imageHint: 'social connection',
    category: 'Social Media',
    isFeatured: true,
    isBestSelling: false,
    releaseDate: '2023-09-15T12:00:00Z',
  },
  {
    id: 'prod_003',
    name: 'LinkedIn Premium',
    slug: 'linkedin-premium',
    description: 'Unlock career opportunities.',
    longDescription: 'Stand out and get in touch with hiring managers. See who\'s viewed your profile, access exclusive salary insights, and get unlimited access to LinkedIn Learning courses.',
    price: 2500,
    originalPrice: 3000,
    imageUrl: 'https://picsum.photos/seed/prod3/600/400',
    imageHint: 'business handshake',
    category: 'Professional',
    isFeatured: false,
    isBestSelling: true,
     releaseDate: '2023-08-20T12:00:00Z',
  },
  {
    id: 'prod_004',
    name: 'Spotify Premium',
    slug: 'spotify-premium',
    description: 'Music without limits.',
    longDescription: 'Listen to music ad-free, play anywhere - even offline. Get unlimited skips and enjoy high-quality audio.',
    price: 800,
    originalPrice: 1000,
    imageUrl: 'https://picsum.photos/seed/prod4/600/400',
    imageHint: 'music notes',
    category: 'Music',
    isFeatured: true,
    isBestSelling: true,
    releaseDate: '2023-10-05T12:00:00Z',
  },
  {
    id: 'prod_005',
    name: 'Netflix Premium',
    slug: 'netflix-premium',
    description: 'Ultra HD streaming on 4 screens.',
    longDescription: 'Watch unlimited movies and TV shows on your phone, tablet, laptop, and TV. Enjoy Ultra HD and watch on four screens at the same time.',
    price: 1800,
    imageUrl: 'https://picsum.photos/seed/prod5/600/400',
    imageHint: 'movie reel',
    category: 'Entertainment',
    isFeatured: false,
    isBestSelling: true,
     releaseDate: '2023-07-11T12:00:00Z',
  },
  {
    id: 'prod_006',
    name: 'X Premium',
    slug: 'x-premium',
    description: 'Get the blue checkmark and more.',
    longDescription: 'Get a boost to your replies, the ability to edit posts, post longer videos, and see half the ads in your timeline. Includes the blue checkmark.',
    price: 750,
    imageUrl: 'https://picsum.photos/seed/prod6/600/400',
    imageHint: 'abstract bird',
    category: 'Social Media',
    isFeatured: true,
    isBestSelling: false,
    releaseDate: '2023-10-10T12:00:00Z',
  },
];

export const orders: Order[] = [
  {
    id: 'ORD-001',
    items: [
      { product: products[0], quantity: 1, recipientEmail: 'user1@example.com' },
      { product: products[3], quantity: 1, recipientEmail: 'friend@example.com' },
    ],
    total: 2000,
    transactionId: 'BK12345XYZ',
    date: '2023-10-26',
    status: 'Completed',
  },
  {
    id: 'ORD-002',
    items: [
      { product: products[2], quantity: 1, recipientEmail: 'professional@example.com' },
    ],
    total: 2500,
    transactionId: 'NG67890ABC',
    date: '2023-10-20',
    status: 'Completed',
  },
];


export const customers: User[] = [
    {
        id: 'user-001',
        name: 'John Doe',
        email: 'john.doe@example.com',
        role: 'customer',
        createdAt: '2023-01-15T10:30:00Z',
    },
    {
        id: 'user-002',
        name: 'Jane Smith',
        email: 'jane.smith@example.com',
        role: 'customer',
        createdAt: '2023-02-20T14:00:00Z',
    },
     {
        id: 'user-003',
        name: 'Admin User',
        email: 'admin@example.com',
        role: 'admin',
        createdAt: '2023-01-01T09:00:00Z',
    },
    {
        id: 'user-004',
        name: 'Alice Johnson',
        email: 'alice.j@example.com',
        role: 'customer',
        createdAt: '2023-03-10T18:45:00Z',
    },
    {
        id: 'user-005',
        name: 'Bob Williams',
        email: 'bob.w@example.com',
        role: 'customer',
        createdAt: '2023-04-05T11:20:00Z',
    },
];
